# -*- coding: utf-8 -*-
"""password generator project_ITvedant.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SyGjg8wPQF6COGLe-R9_QHBGZBN3TrmF
"""

import random

chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890!@#$%^&*()_+{}"

while 1:
    password_len = int(input('What length would you like your password to be : '))
    password_count = int(input('How many password would you like : '))
    for x in range(0, password_count):
        password = ""
        for x in range(0, password_len):
          password_char = random.choice(chars)
          password  =password + password_char
        print('Here is your password : ', password)

